---
version: 2
plan:
  project-key: PROM
  key: PROM
  name: PrometheusBuildPlan
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Build and Compile Job
Build and Compile Job:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: 'false'
      description: Checkout Project-level Repository
  - command:
      executable: dotnet
      argument: restore PrometheusPlayground.sln
      description: Restore nuget packages used in the solution
  - command:
      executable: dotnet
      argument: publish /p:PublishRootDir=${bamboo.build.working.directory}/artifacts PrometheusPlayground.sln /p:Configuration="${bamboo.Configuration}" /p:target="${bamboo.Target}"
      description: Build solution and publishing artifacts
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
      - |-
        echo $PWD
        zip -r artifacts.zip artifacts
        ls -l
      description: Archive project artifacts into zip file
  - command:
      executable: dotnet
      argument: test PrometheusPlayground.sln --logger "trx;LogFileName=testresults.trx"
      description: Run tests on the solution
  - command:
      executable: Code Coverage
      argument: inspectcode PrometheusPlayground.sln --severity=WARNING --build -o=inspectcode.xml --include=**/*.cs
      description: Collect code issues 
  final-tasks:
  - any-task:
      plugin-key: com.atlassian.bamboo.plugin.dotnet:mstest
      configuration:
        mstestTestResultsDirectory: '**/*.trx'
        pickupOutdatedFiles: 'false'
      description: Parse test results
  artifacts:
  - name: Binaries
    pattern: artifacts.zip
    shared: true
    required: true
  - name: Code Inspection
    pattern: inspectcode.xml
    shared: true
    required: true
  artifact-subscriptions: []
variables:
  Configuration: Release
  Target: Any CPU
repositories:
- PrometheusPayloadGitHub:
    scope: project
triggers:
- polling:
    period: '180'
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
...  